- name: Deploy Invision Community Suite sources
  hosts: "{{ host }}"
  vars:
    - dump_file_name: "{{ inventory_hostname }}-ipb-{{ ansible_date_time.iso8601_basic_short }}"

  tasks:

  - name: remove sources locally
    local_action:
      module: file
      path: "omskvelo-forum"
      state: absent

  - name: git clone locally
    local_action:
      module: git
      repo: "git@bitbucket.org:ivanzoid/omskvelo-forum.git"
      dest: "omskvelo-forum"
      depth: 1
      version: "{{ ipb_version }}"

  - name: remove .git locally
    local_action:
      module: file
      path: "omskvelo-forum/.git"
      state: absent

  - name: make backup 
    archive:
      path: "{{ ipb_location }}"
      dest: "/tmp/{{ dump_file_name }}.tgz"
    become: true

  - name: remove dir
    file:
      path: "{{ ipb_location }}"
      state: absent
    become: true

  - name: create dir
    file:
      path: "{{ ipb_location }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    become: true

  - name: copy sources
    synchronize:
      src: omskvelo-forum/
      dest: "{{ ipb_location }}"

  - name: remove sources locally
    local_action:
      module: file
      path: "omskvelo-forum"
      state: absent

  - name: update dir permissions
    file:
      path: "{{ forum_location }}"
      state: directory
      recurse: yes
      owner: "{{ omskvelo_unix_user }}"
      group: "{{ omskvelo_unix_group }}"
    become: true

  - name: update other dir permissions
    file:
      path: '{{ item }}'
      state: directory
      owner: "{{ omskvelo_unix_user }}"
      group: "{{ omskvelo_unix_group }}"
      mode: 0770
    with_items:
      - "{{ forum_location }}/datastore"
      - "{{ forum_location }}/uploads"
      - "{{ forum_location }}/uploads/logs"
      - "{{ ipb_location }}/plugins"
    become: true

  - name: create more dirs
    file:
      path: '{{ forum_location }}/uploads/{{ item }}'
      state: directory
      owner: "{{ omskvelo_unix_user }}"
      group: "{{ omskvelo_unix_group }}"
      mode: 0770
    with_items:
      - react 
      - profile_fields 
      - club_images 
      - club_fields 
      - ads 
      - social_images 
      - image_proxy 
      - emoji 
      - profile 
      - files 
      - login_icons 
      - icons 
      - calendar_covers
    become: true

  - name: Link IPB configuration
    file:
      src: "../{{ item }}"
      dest: "{{ ipb_location }}/{{ item }}"
      state: link
      force: yes
    with_items: "{{ ipb_config_files }}"
