- name: Export IPB uploads folder
  hosts: "{{ host }}"

  vars:
    - dump_file_name: "{{ inventory_hostname }}-uploads-{{ ansible_date_time.iso8601_basic_short }}"

  tasks:
  
  - name: Compress dump
    archive:
      path: "{{ ipb_uploads_location }}"
      dest: "/tmp/{{ dump_file_name }}.tgz"
    become: true

  - name: Download file
    fetch:
      src: "/tmp/{{ dump_file_name }}.tgz"
      dest: "{{ dump_file_name }}.tgz"
      flat: yes

  - name: Remove tmp file
    file:
      state: absent
      path: "/tmp/{{ dump_file_name }}.tgz"
    become: true

