- name: Install Python
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install Python 2
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout