- name: Create database
  mysql_db:
    name: "{{ omskvelo_sql_db }}"
    encoding: utf8mb4
    state: present

- name: Create MySQL user
  mysql_user:
    name: "{{ omskvelo_sql_user }}"
    password: "{{ omskvelo_sql_password }}"
    priv: "{{ omskvelo_sql_db }}.*:ALL"
    state: present

- name: Fix sql_mode
  command: mysql --execute "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
